# GitLab CI/CD Pipeline for Java Spring Boot Application with Docker

# Define pipeline stages
stages:
  - build
  - test
  - deploy

backend:build:
  stage: build
  image: gradle:8.3-jdk24
  script:
    - echo "Building Spring Boot backend..."
    - cd backend
    - ./gradlew.bat clean bootJar --no-daemon
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: 1 hour
  only:
    - develop    
    - merge_requests


frontend:build:
  stage: build
  image: node:22-alpine
  script:
    - echo "Building Vite + React frontend..."
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hour
  only:
    - develop    
    - merge_requests  


unit-tests:
  stage: test
  image: gradle:8.3-jdk24
  script:
    - echo "Running tests with Mockito..."
    - cd backend
    - ./gradlew clean test --no-daemon
  # cache:
  #   policy: pull  
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/TEST-*.xml
    paths:
      - backend/build/reports/tests/test

# later implement deploy      

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

