# GitLab CI/CD Pipeline for Java Spring Boot Application with Docker

# Define pipeline stages
stages:
  - build
  - test
  - deploy

backend:build:
  stage: build
  image: gradle:8.3-jdk24
  script:
    - echo "Building Spring Boot backend..."
    - ./gradlew clean bootJar --no-daemon
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: 1 hour
  only:
    - main
    - develop    

frontend:build:
  stage: build
  image: node:22-alpine
  script:
    - echo "Building Vite + React frontend..."
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hour



unit-tests:
  stage: test
  image: gradle:8.3-jdk24
  script:
    - echo "Running tests with Mockito..."
    - cd backend
    - ./gradlew clean bootJar --no-daemon
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/TEST-*.xml
    paths:
      - backend/build/reports/tests/test
  only:
    - main
    - develop  
