services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_FLYWAY_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_USER: ${SPRING_DATASOURCE_USERNAME}
      SPRING_FLYWAY_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      JWT_SECRET: ${JWT_SECRET}

      GRAPHHOPPER_BASE_URL: https://graphhopper.com/api/1/route
      GRAPHHOPPER_API_KEY: ${GRAPHHOPPER_API_KEY}

      AWS_S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      AWS_S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: us-east-1
      BUCKET_NAME: digicompassip
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_PUBLIC_ENDPOINT: http://localhost:9000

    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      createbuckets:
        condition: service_completed_successfully
    networks:
      - app-network

  db:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_DB: digicompass
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - app-network
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
      mc mb --ignore-existing local/digicompassip
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
