stages:
  - build
  - test
  - sonar
  - deploy

backend:build:
  stage: build
  image: gradle:8.3-jdk24
  script:
    - echo "Building Spring Boot backend..."
    - cd backend
    - ./gradlew clean bootJar --no-daemon

unit-tests:
  stage: test
  image: gradle:8.3-jdk24
  script:
    - echo "Running tests with Mockito..."
    - cd backend
    - ./gradlew test --no-daemon
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/TEST-*.xml
    paths:
      - backend/build/reports/tests/test

integration-tests:
  stage: test
  image: gradle:8.3-jdk24
  script:
    - echo "Running Integration tests..."
    - cd backend
    - ./gradlew integrationTest --no-daemon
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/integrationTest/TEST-*.xml
    paths:
      - backend/build/reports/tests/integrationTest

sonarcloud-analysis:
  stage: sonar
  image: gradle:8.3-jdk24
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo "Running SonarCloud analysis..."
    - cd backend
    - ./gradlew test integrationTest jacocoTestReport --no-daemon
    - ./gradlew sonar --no-daemon
  only:
    - main
    - development
  allow_failure: true

docker-backend:build-and-push:
  stage: deploy
  image: docker:26.1.3
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - echo "Building Docker backend image..."
    - docker build -t $DOCKERHUB_USERNAME/digicompass-backend:latest -t $DOCKERHUB_USERNAME/digicompass-backend:$CI_COMMIT_SHORT_SHA backend
    - echo "Pushing backend image to Docker Hub..."
    - docker push $DOCKERHUB_USERNAME/digicompass-backend:latest
    - docker push $DOCKERHUB_USERNAME/digicompass-backend:$CI_COMMIT_SHORT_SHA
  only:
    - main