
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.DigiCompass'
version = '0.0.1-SNAPSHOT'
description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

configurations {
    mockitoAgent {
        transitive = false
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok:1.18.40'
    annotationProcessor 'org.projectlombok:lombok:1.18.40'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'de.mkammerer:argon2-jvm:2.1'
    implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
    implementation 'com.github.dozermapper:dozer-core:7.0.0'
    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'

    // Mockito (same version for all)
    testImplementation 'org.mockito:mockito-core:5.20.0'
    testImplementation 'org.mockito:mockito-inline:5.2.0'       // for static mocking
    testImplementation 'org.mockito:mockito-junit-jupiter:5.20.0'   // MockitoExtension

    testImplementation 'org.springframework.boot:spring-boot-starter-test'


}


tasks.named('test', Test) {
    useJUnitPlatform()




    testLogging {
        events "passed", "skipped", "failed", "standardError"
        exceptionFormat "full"
        showExceptions true
        showCauses true
        showStackTraces true
        showStandardStreams = true
    }
}
