# Build stage
FROM eclipse-temurin:24-jdk-alpine AS builder

WORKDIR /back-end

# Copy Gradle wrapper and build files
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x gradlew && ./gradlew dependencies --no-daemon

# Copy source code
COPY src src

# Build the application
RUN ./gradlew bootJar --no-daemon

WORKDIR /app

EXPOSE 8080

# Runtime Stage
FROM eclipse-temurin:24-jre-alpine

WORKDIR /app

# Copy the built JAR file from the builder stage
COPY build/libs/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]

