# Build stage
FROM eclipse-temurin:24-jdk-alpine

WORKDIR /back-end

# Copy Gradle wrapper and build files
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x gradlew && ./gradlew dependencies --no-daemon || true

# Copy source code
COPY src src

WORKDIR /app

EXPOSE 8080

CMD ["./gradlew", "bootRun", "--no-daemon"]
