CREATE TABLE trip
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(80)                             NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    planned_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    route_id      BIGINT                                  NOT NULL,
    accessibility BOOLEAN                                 NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_trip PRIMARY KEY (id)
);

ALTER TABLE trip
    ADD CONSTRAINT FK_TRIP_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE trip
    ADD CONSTRAINT FK_TRIP_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


ALTER TABLE users
ALTER
COLUMN bio TYPE VARCHAR(255) USING (bio::VARCHAR(255));

ALTER TABLE users
    ALTER COLUMN is_public_profile SET NOT NULL;