CREATE TABLE rating
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating             DOUBLE PRECISION                        NOT NULL,
    created_by_user_id BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    route_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_rating PRIMARY KEY (id)
);

CREATE TABLE review
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    review             VARCHAR(255)                            NOT NULL,
    created_by_user_id BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    route_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE TABLE review_images
(
    images_id        BIGINT NOT NULL,
    review_entity_id BIGINT NOT NULL
);

CREATE TABLE route_images
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url VARCHAR(255)                            NOT NULL,
    route_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_route_images PRIMARY KEY (id)
);

CREATE TABLE routes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name               VARCHAR(255)                              NOT NULL,
    description        VARCHAR(255),
    route_type         VARCHAR(255)                              NOT NULL,
    difficulty         VARCHAR(255)                              NOT NULL,
    distance           FLOAT                                     NOT NULL,
    duration           VARCHAR(255)                              NOT NULL,
    created_by_user_id BIGINT                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    route_geometry     GEOMETRY,
    CONSTRAINT pk_routes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    birth_date date                                    NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE routes
    ADD CONSTRAINT uc_routes_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE route_images
    ADD CONSTRAINT FK_ROUTE_IMAGES_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE review_images
    ADD CONSTRAINT fk_revima_on_review_entity FOREIGN KEY (review_entity_id) REFERENCES review (id);

ALTER TABLE review_images
    ADD CONSTRAINT fk_revima_on_route_image_entity FOREIGN KEY (images_id) REFERENCES route_images (id);