ALTER TABLE review_images
    DROP CONSTRAINT fk_revima_on_review_entity;

ALTER TABLE review_images
    DROP CONSTRAINT fk_revima_on_route_image_entity;

ALTER TABLE review_images
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE review_images
    ADD image_url VARCHAR(255);

ALTER TABLE review_images
    ADD review_id BIGINT;

ALTER TABLE review_images
    ALTER COLUMN image_url SET NOT NULL;

ALTER TABLE review_images
    ALTER COLUMN review_id SET NOT NULL;

ALTER TABLE review_images
    ADD CONSTRAINT pk_review_images PRIMARY KEY (id);

ALTER TABLE review_images
    ADD CONSTRAINT FK_REVIEW_IMAGES_ON_REVIEW FOREIGN KEY (review_id) REFERENCES review (id);

ALTER TABLE review_images
    DROP COLUMN images_id;

ALTER TABLE review_images
    DROP COLUMN review_entity_id;

ALTER TABLE users
    ALTER COLUMN birth_date SET NOT NULL;