CREATE TABLE routes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    route_type         VARCHAR(255)                            NOT NULL,
    difficulty         VARCHAR(255)                            NOT NULL,
    distance           FLOAT                                   NOT NULL,
    duration           VARCHAR(255)                            NOT NULL,
    start_location     VARCHAR(255)                            NOT NULL,
    end_location       VARCHAR(255)                            NOT NULL,
    created_by_user_id BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_routes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username           VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    age                INTEGER                                 NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    reset_token        VARCHAR(255),
    reset_token_expiry TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE routes
    ADD CONSTRAINT uc_routes_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);