

CREATE TABLE route_images
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url VARCHAR(255)                            NOT NULL,
    route_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_route_images PRIMARY KEY (id)
);

CREATE TABLE routes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    route_type         VARCHAR(255)                            NOT NULL,
    difficulty         VARCHAR(255)                            NOT NULL,
    distance           FLOAT                                   NOT NULL,
    duration           VARCHAR(255)                            NOT NULL,
    created_by_user_id BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    route_geometry     GEOMETRY,
    CONSTRAINT pk_routes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    birth_date        date                                    NOT NULL,
    password          VARCHAR(255)                            NOT NULL,
    role_id           BIGINT,
    image_url         VARCHAR(255),
    bio               VARCHAR(255),
    is_public_profile BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_role UNIQUE (role);

ALTER TABLE routes
    ADD CONSTRAINT uc_routes_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE review_images
    ADD CONSTRAINT FK_REVIEW_IMAGES_ON_REVIEW FOREIGN KEY (review_id) REFERENCES review (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE route_images
    ADD CONSTRAINT FK_ROUTE_IMAGES_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);