spring.config.import=optional:classpath:.env.properties

# application.properties

#docker
spring.datasource.url=jdbc:postgresql://localhost:5434/digicompass
spring.datasource.username=postgres
spring.datasource.password=dbyT56@
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.data-source-properties.sslmode=disable
#fixing the too many clients problem with the db
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=musaaleyna1@gmail.com
spring.mail.password=xgdm exnf ruxh pkcm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#aws s3
aws.access.key=${AWS_S3_ACCESS_KEY}
aws.secret.key=${AWS_S3_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=${BUCKET_NAME}

google.maps.api.key=${GOOGLE_MAPS_API_KEY}

#JWT
jwt.secret=${JWT_SECRET}
#30 min
jwt.expiration-ms=1800000
#7days
jwt.refresh-expiration-ms=604800000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

graphhopper.base-url=https://graphhopper.com/api/1/route
graphhopper.api-key=${GRAPHHOPPER_API_KEY}

